# Generated by Django 4.2.4 on 2023-08-28 15:39

from django.db import migrations, models
import items.models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='next_date',
            field=models.DateField(default=items.models.Item.calculate_next_date, editable=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='stage',
            field=models.IntegerField(choices=[(0, 'Initial'), (1, 'Day 1'), (7, 'Day 7'), (16, 'Day 16'), (35, 'Day 35')], default=0, editable=False),
        ),
    ]
