# Generated by Django 4.2.4 on 2023-08-27 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='stage',
            field=models.IntegerField(choices=[(0, 'Initial'), (1, 'Day 1'), (7, 'Day 7'), (16, 'Day 16'), (35, 'Day 35')], default=0),
        ),
    ]
