# Generated by Django 4.2.4 on 2023-09-03 13:47

from django.db import migrations, models
import items.models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='init_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='next_date',
            field=models.DateTimeField(default=items.models.Item.calculate_next_date, editable=False),
        ),
    ]
