# Generated by Django 4.2.4 on 2023-08-27 20:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_item_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='init_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
