# Generated by Django 4.2.4 on 2023-08-27 20:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_item_init_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='init_date',
        ),
        migrations.AddField(
            model_name='item',
            name='init_date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
