# Generated by Django 4.2.4 on 2023-08-27 21:11

from django.db import migrations, models
import django.utils.timezone
import items.models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_remove_item_init_date_item_init_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='init_date_time',
        ),
        migrations.AddField(
            model_name='item',
            name='init_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='next_date',
            field=models.DateField(default=items.models.Item.calculate_next_date),
        ),
    ]
